receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'spring-petclinic'
          scrape_interval: 5s
          metrics_path: /actuator/prometheus
          static_configs:
            - targets: ['localhost:8080']
  filelog:
    include: ["/var/log/app/app.log"]
    start_at: beginning
    operators:
      - type: regex_parser
        regex: '^(?P<timestamp>\d{2}:\d{2}:\d{2}\.\d{3}) trace_id=(?P<trace_id>\w+) span_id=(?P<span_id>\w+) trace_flags=(?P<trace_flags>\w+) (?P<message>.*)$'
        timestamp:
          parse_from: attributes.timestamp
          layout: '%H:%M:%S.%L'

processors:
  batch:

exporters:
  awsxray:
  awsemf:
    log_group_name: "/aws/ecs/spring-petclinic"
    log_stream_name: "adot-metrics"
    namespace: "SpringPetClinic"
  awscloudwatchlogs:
    log_group_name: "/aws/ecs/spring-petclinic"
    log_stream_name: "adot-logs"
    region: "ap-northeast-1"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [awsemf]
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [awscloudwatchlogs]
