extensions:
  sigv4auth:
    service: "aps"
    region: "ap-northeast-1"
  health_check:
    endpoint: "0.0.0.0:13133"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'spring-petclinic'
          scrape_interval: 30s
          metrics_path: /actuator/prometheus
          static_configs:
            - targets: ['localhost:8080']
        - job_name: 'otel'
          scrape_interval: 30s
          metrics_path: /metrics
          static_configs:
            - targets: ['localhost:9464']
  awsecscontainermetrics:
    collection_interval: 30s
  # filelog:
  #   include: ["/var/log/app/app.log"]
    # start_at: beginning
    # operators:
    #   - type: regex_parser
    #     regex: '^(?P<timestamp>\d{2}:\d{2}:\d{2}\.\d{3}) trace_id=(?P<trace_id>\w+) span_id=(?P<span_id>\w+) trace_flags=(?P<trace_flags>\w+) (?P<message>.*)$'
    #     timestamp:
    #       parse_from: attributes.timestamp
    #       layout: '%H:%M:%S.%L'

processors:
  batch:

exporters:
  awsxray:
    region: ap-northeast-1
  awsemf:
    log_group_name: "/aws/ecs/spring-petclinic"
    log_stream_name: "adot-metrics"
    namespace: "SpringPetClinic"
  prometheusremotewrite:
    endpoint: "https://aps-workspaces.ap-northeast-1.amazonaws.com/workspaces/ws-3a53e980-2983-458b-88ce-1956a5dcd9e0/api/v1/remote_write"
    auth:
      authenticator: sigv4auth
  prometheusremotewrite/thanos:
    endpoint: "http://10.111.1.212:31700/api/v1/receive"
    tls:
      insecure: true
    headers:
      THANOS-TENANT: "ecs-tenant"
  # awscloudwatchlogs:
  #   log_group_name: "/aws/ecs/spring-petclinic"
  #   log_stream_name: "adot-logs"
  #   region: "ap-northeast-1"
  otlp:
    endpoint: 10.111.1.179:4317
    tls:
      insecure: true
  otlphttp:
    endpoint: http://10.111.1.179:4318
    tls:
      insecure: true
  # otlphttp/logs:
  #   endpoint: "http://10.111.1.179:3100/otlp"
  #   tls:
  #     insecure: true

service:
  extensions: [sigv4auth,health_check]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray,otlp,otlphttp]
    metrics:
      receivers: [otlp,prometheus,awsecscontainermetrics]
      processors: [batch]
      exporters: [awsemf,prometheusremotewrite,prometheusremotewrite/thanos]
    # logs:
    #   receivers: [filelog]
    #   processors: [batch]
    #   exporters: [awscloudwatchlogs,otlphttp/logs]
