extensions:
  sigv4auth:
    service: "aps"
    region: "ap-northeast-1"

receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'spring-petclinic'
          scrape_interval: 30s
          metrics_path: /actuator/prometheus
          static_configs:
            - targets: ['localhost:8080']
        - job_name: 'otel'
          scrape_interval: 30s
          metrics_path: /metrics
          static_configs:
            - targets: ['localhost:9464']
  awsecscontainermetrics:
    collection_interval: 30s
  filelog:
    include: ["/var/log/app/app.log"]
    start_at: beginning
    operators:
      - type: regex_parser
        regex: '^(?P<timestamp>\d{2}:\d{2}:\d{2}\.\d{3}) trace_id=(?P<trace_id>\w+) span_id=(?P<span_id>\w+) trace_flags=(?P<trace_flags>\w+) (?P<message>.*)$'
        timestamp:
          parse_from: attributes.timestamp
          layout: '%H:%M:%S.%L'

processors:
  batch:

exporters:
  awsxray:
    region: ap-northeast-1
  awsemf:
    log_group_name: "/aws/ecs/spring-petclinic"
    log_stream_name: "adot-metrics"
    namespace: "SpringPetClinic"
  prometheusremotewrite:
    endpoint: "https://aps-workspaces.ap-northeast-1.amazonaws.com/workspaces/ws-3a53e980-2983-458b-88ce-1956a5dcd9e0/api/v1/remote_write"
    auth:
      authenticator: sigv4auth
  awscloudwatchlogs:
    log_group_name: "/aws/ecs/spring-petclinic"
    log_stream_name: "adot-logs"
    region: "ap-northeast-1"
  otlp:
    endpoint: 10.111.1.179:4317

service:
  extensions: [sigv4auth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray,otlp]
    metrics:
      receivers: [otlp,prometheus,awsecscontainermetrics]
      processors: [batch]
      exporters: [awsemf,prometheusremotewrite]
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [awscloudwatchlogs]
